version: '2'
services:
        seng-runtime:
                image: seng/runtime
                container_name: seng-runtime
                privileged: true
                cap_add:
                    - SYS_RAWIO
                #TODO: for testing with localhost
                network_mode: "host"
                build: .
                ports:
                    # for nginx
                    - "4711:4711/tcp"
                    - "3443:3443/tcp"
                    #TODO
                    - "2834:2834/tcp"
                devices:
                        - "/dev/isgx:/dev/isgx"
                        - "/dev/mei0:/dev/mei0"
                        - "/dev/gsgx:/dev/gsgx"
                volumes:
                    - /var/run/aesmd:/var/run/aesmd
                    - ../sgx-ra-tls:/home/encl-dev/sgx-ra-tls
                    - .:/home/encl-dev/client_enclave
                    - ../benchmarking:/home/encl-dev/benchmarking
                    - ../seng_server/double_tunnel_openssl/src/seng.proto:/home/encl-dev/seng_server/double_tunnel_openssl/src/seng.proto
                    - ../seng_server/srv_cert.pem:/home/encl-dev/sgx-ra-tls/middlebox_cert.pem

