version: '2'
services:
        base-container:
                image: seng/baseimage
                container_name: sengbase
                privileged: false
                build: .
                volumes:
                    - ../sgx-ra-tls:/home/encl-dev/sgx-ra-tls
